insert into component (ITEM_CODE, NAME, PRICE, QUANTITY, TYPE, VALUE) values ('1234', 'Asus', 4990,	 2, 'Maticna ploca','REQUIRED_ONE')
insert into component (ITEM_CODE, NAME, PRICE, QUANTITY, TYPE, VALUE) values ('4321', 'Intel', 14999,	 1, 'Procesor','REQUIRED_ONE')
insert into component (ITEM_CODE, NAME, PRICE, QUANTITY, TYPE, VALUE) values ('5678', 'Dell', 18499,	 3, 'Monitor','REQUIRED_ONE')
insert into component (ITEM_CODE, NAME, PRICE, QUANTITY, TYPE, VALUE) values ('8765', 'Seagate', 4500,	 5, 'HDD','REQUIRED_N')
insert into component (ITEM_CODE, NAME, PRICE, QUANTITY, TYPE, VALUE) values ('1928', 'Samsung', 8990,	 0, 'SSD','OPTIONAL_N')
insert into component (ITEM_CODE, NAME, PRICE, QUANTITY, TYPE, VALUE) values ('1928', 'MSI GTX GAMING', 26990,	 6, 'GUI','OPTIONAL_N')
insert into user(firstname, lastname, email, number, password, user_role, address, payment_type, grad) values('Rade','Spasojevic','radespasoje@gmail.com','064/279-66-77','crninovembar','ADMIN','Svetozara Miletica 43/14','KREDITNA_KARTICA','Novi Sad')
insert into user(firstname, lastname, email, number, password, user_role, address, payment_type, grad) values('Ana','Mitrovic','anchy93@gmail.com','064/3100-88-66','princeza','ADMIN','Ante Bogicevica 2/2','POZECEM','Sabac')
insert into user(firstname, lastname, email, number, password, user_role, address, payment_type, grad) values('Bruce','Wayne','batman@gmail.com','++381642896677','batman','USER','BatCave Null','UPLATANARACUN', 'Gotham')
